create table if not exists users (
  telegram_id bigint primary key,
  username text,
  first_name text,
  balance numeric(18,2) not null default 0,
  regular_ads integer not null default 0,
  withdrawal_ads integer not null default 0,
  boost_ads integer not null default 0,
  boost_until timestamptz,
  last_regular_ad_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists ad_rewards (
  id bigint generated by default as identity primary key,
  reward_id text not null unique,
  telegram_id bigint not null references users(telegram_id) on delete cascade,
  ad_type text not null check (ad_type in ('regular','boost','withdrawal')),
  amount numeric(18,2) not null,
  provider text not null default 'monetag',
  created_at timestamptz not null default now()
);

create table if not exists withdrawals (
  id bigint generated by default as identity primary key,
  telegram_id bigint not null references users(telegram_id) on delete cascade,
  amount numeric(18,2) not null,
  binance_id text not null,
  status text not null default 'Pending',
  created_at timestamptz not null default now()
);

create index if not exists ad_rewards_user_idx on ad_rewards(telegram_id, created_at desc);
create index if not exists withdrawals_user_idx on withdrawals(telegram_id, created_at desc);

alter table users enable row level security;
alter table ad_rewards enable row level security;
alter table withdrawals enable row level security;

create or replace function apply_ad_reward(
  p_reward_id text,
  p_telegram_id bigint,
  p_ad_type text,
  p_amount numeric
) returns jsonb
language plpgsql
security definer
as $$
declare
  already boolean;
  new_balance numeric;
  new_regular integer;
  new_withdrawal integer;
  new_boost integer;
begin
  select exists(select 1 from ad_rewards where reward_id=p_reward_id) into already;
  if already then
    return jsonb_build_object('ok',true,'duplicate',true);
  end if;

  insert into users(telegram_id) values(p_telegram_id)
  on conflict (telegram_id) do nothing;

  insert into ad_rewards(reward_id,telegram_id,ad_type,amount)
  values(p_reward_id,p_telegram_id,p_ad_type,p_amount);

  update users set
    balance = balance + p_amount,
    regular_ads = regular_ads + case when p_ad_type='regular' then 1 else 0 end,
    withdrawal_ads = withdrawal_ads + case when p_ad_type='withdrawal' then 1 else 0 end,
    boost_ads = boost_ads + case when p_ad_type='boost' then 1 else 0 end,
    updated_at=now()
  where telegram_id=p_telegram_id
  returning balance,regular_ads,withdrawal_ads,boost_ads
  into new_balance,new_regular,new_withdrawal,new_boost;

  return jsonb_build_object(
    'ok',true,'duplicate',false,'balance',new_balance,
    'regular_ads',new_regular,'withdrawal_ads',new_withdrawal,'boost_ads',new_boost
  );
end;
$$;
